"""23 个人体关键点名称（球拍与击球点使用独立接触几何标注）。"""

KEYPOINT_NAMES = (
    "head_top",
    "head_center",
    "chin",
    "neck",
    "chest_center",
    "spine_mid",
    "pelvis_center",
    "left_shoulder",
    "left_elbow",
    "left_wrist",
    "left_palm",
    "right_shoulder",
    "right_elbow",
    "right_wrist",
    "right_palm",
    "left_hip",
    "left_knee",
    "left_ankle",
    "left_toe",
    "right_hip",
    "right_knee",
    "right_ankle",
    "right_toe",
)
